language: ruby
rvm:
  - 2.4.0
script:
  - bundle exec rake db:create db:migrate
  - bundle exec rake spec
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp ci/database.yml.travis config/database.yml
services:
  - postgresql
addons:
  postgresql: '9.4'
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
